name: Publish
on:
  push:
    branches:
      - "master"

jobs:
  publish:
    runs-on: ubuntu-20.04
    name: Publish
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: |
          yarn -v
          yarn

      - name: Apply semver updates (if any)
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          if yarn auto version; then
            AUTO_VERSION=$(yarn auto version)
            echo "Auto Version: $AUTO_VERSION"
            if [[ $AUTO_VERSION == pre* ]]; then
              yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes --preid "$GITHUB_REF"
            elif [[ $AUTO_VERSION ]]; then
              yarn lerna version "$AUTO_VERSION" --no-git-tag-version --no-push --yes
            fi
          else
            echo "Unable to bump version successfully." && exit 1
          fi

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn build
          yarn install --frozen-lockfile --non-interactive --cache-folder=~/.cache/yarn
          yarn auto shipit
